/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Variant({
  'watches' : IDL.Null,
  'caps' : IDL.Null,
  'sunglasses' : IDL.Null,
  'clothes' : IDL.Null,
});
export const Product = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : Category,
  'price' : IDL.Text,
});
export const Review = IDL.Record({
  'customerName' : IDL.Text,
  'reviewText' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getAllReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
  'getProductsByCategory' : IDL.Func([Category], [IDL.Vec(Product)], ['query']),
  'initializeStore' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Variant({
    'watches' : IDL.Null,
    'caps' : IDL.Null,
    'sunglasses' : IDL.Null,
    'clothes' : IDL.Null,
  });
  const Product = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : Category,
    'price' : IDL.Text,
  });
  const Review = IDL.Record({
    'customerName' : IDL.Text,
    'reviewText' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getAllReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
    'getProductsByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'initializeStore' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };